name: Docker Image CI

on:
  push:
    branches: [ "producao", "homologacao" ]
  pull_request:
    branches: [ "producao", "homologacao" ]

env:
  KUBE_CONFIG: ${{ github.ref_name == 'producao' && secrets.KUBE_CONFIG || secrets.KUBE_CONFIG_HML}}
  NAMESPACE: ${{ github.ref_name == 'producao' && 'thalamus-prd' || 'thalamus-hml' }}
  AMBIENTE:  ${{ github.ref_name == 'producao' && 'production' || 'staging' }}
  IMAGE_TAG:  ${{ github.ref_name == 'producao' && 'latest' || 'hml' }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Faz o build da imagem 
    - name: Build imagem docker
      run: docker build . --build-arg AMBIENTE=${{ env.AMBIENTE }} -t devroboflex/thalamus-produtos-frontend:${{ env.IMAGE_TAG }}

    - name: Push imagem docker 
      run: docker push devroboflex/thalamus-portal-frontend:${{ env.IMAGE_TAG }}

    - name: Setup kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ env.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Deploy 
      run: |
        kubectl -n ${{ env.NAMESPACE }} rollout restart deployment/thalamus-produtos